name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  hadolint:
    name: Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          config: .hadolint.yaml
          failure-threshold: warning
          ignore: DL3006 DL3008 DL3013 DL3059 SC3010 DL3022 DL3002 DL3003 DL3018
